server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    hikari:
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:mysql://34.135.81.32:3306/stockServer
      jdbc-url: jdbc:mysql://server.dbsg.co.kr:3306/stockServer
      #jdbc-url: jdbc:log4jdbc:mysql://34.135.81.32:3306/stockServer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: everywhere
      password: everypw
      #username: admin
      #password: P@ssVV0rd
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
Mybatis:
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  #옵션설명: https://springdoc.org/properties.html
  swagger-ui:
    path: /doc
  #packages-to-scan: *
  paths-to-match: /api/v1/**, /login/**

jwt:
  secret: anNvbi10b2tlbi1zZWNyZXQta2V5LWluLWRic2ctYXBpLWJhc2U2NC1xYXp4c3dlZGN2ZnJ0Z2JuaHl1am1raW9scC0wOTg3NjU0MzIxLWp3dC1zdG9ja3NlcnZlcgo=
