server:
  port: 8080
spring:
  profiles:
    default: local
    group:
      local:
        - secret
      dev:
        - secret
      prod:
        - secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
Mybatis:
  configuration:
    map-underscore-to-camel-case: true

# swagger (https://springdoc.org/properties.html)
springdoc:
  swagger-ui:
    path: /doc
  paths-to-match: /api/v1/**, /login/**
swagger:
  title: 공모주토피아 API
  version: v0.4.1
  description: 주식알리미 서비스에 사용되는 API 명세입니다. 전체 response는 공통반환 클래스의 body 내부에 들어가게 됩니다. <br/> <a href='https://www.notion.so/9c74d32d5e9846d698757d8b23cb0108?v=065595755f7645028e0a191479d986fa'>서버 변동사항 정리</a><br/> <a href='https://github.com/chhs2131/dbsgAPI'>소스코드 변동내역(Github)</a>

# jwt
jwt:
  token-valid-time: 1800000  # 1달
  authorities-key: auth
  header: Bearer

# social
social:
  kakao:
    baseUrl: https://kapi.kakao.com
    token:
      path: /v1/user/access_token_info
      method: GET
    profile:
      path: /v2/user/me
      method: GET
